---

- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - include: tasks/pre_update.yml


- hosts: localhost
  connection: local
  become: true
  tasks:
  - include: tasks/users.yml
  - include: tasks/cron.yml
  - include: tasks/packages_ansible.yml
  - include: tasks/packages_basic.yml
  - include: tasks/packages_workstation.yml
  - include: tasks/packages_VM_QEMU-KVM.yml
#  - include: tasks/packages_server-basic.yml
