---

- hosts: localhost
  connection: local
#  become: sandro
  gather_facts: true
  pre_tasks:
  - include: tasks/config_workstation-getFacts.yml


- hosts: localhost
  connection: local
  become: true
  tags: startall,pre
  pre_tasks:
    - include: tasks/config_workstation-addrepos.yml
    - include: tasks/update_all.yml


- hosts: localhost
  connection: local
  become: true
  tags: startall
  tasks:

#   ssh, ansible, git ... muss bereits vorhanden sein
#  - include: tasks/packages_all-ansible.yml
  - include: tasks/config_all-users.yml
  - include: tasks/config_all-cron.yml
  - include: tasks/packages_all-basic.yml
  - include: tasks/packages_workstation.yml
  - include: tasks/packages_workstation-additional.yml
  - include: tasks/config_workstation-snap.yml
  - include: tasks/packages_workstation-snap.yml
  - include: tasks/config_workstation-flatpak.yml
  - include: tasks/packages_workstation-flatpak.yml
  - include: tasks/packages_workstation-gnomeshellstuff.yml
  - include: tasks/packages_all-VM-QemuKvm.yml
  - include: tasks/packages_workstation-VM-QemuKvm.yml
  - include: tasks/config_all-firewall.yml
  - include: tasks/config_workstation-firewall.yml
  - include: tasks/cleanup_all.yml
#  - include: tasks/reboot_all.yml


- hosts: localhost
  connection: local
  become: sandro
  tags: gnome, gnome-shell
  tasks:
  - include: tasks/packages_workstation-gnomeshellExtensions.yml
