---

- hosts: localhost
  connection: local
  become: true
  pre_tasks:

    - name: update repository index and update Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
#        when: ansible_distribution_version == "Ubuntu"
#        when: ansible_os_family == "Debian"
      when: ansible_pkg_mgr == "apt"

    - name: update repository index and update (open)SUSE
      zypper:
        update_cache: yes
        state: dist-upgrade
#        when: ansible_distribution_version == "Suse"
#        when: ansible_os_family == "Suse"
      when: ansible_pkg_mgr == "zypper"


- hosts: localhost
  connection: local
  become: true

  tasks:
### Installation:
  - name: install packages
    package:
      state: latest
### basic
      name:
        - clamav
        - git
        - htop
        - nano
        - neofetch
        - openssh-client
        - rsync
        - ssh
#       Automation:
        - ansible
#       Automation apt (Ubuntu, Debian, ...)
        - python-apt
        - python3-apt
        - aptitude
#       Automation zypper (openSUSE, ...)
#        - python-xml
#        - rpm
###    Desktop/Laptop
        - clamtk
        - gimp
        - gimp-help-de
        - gparted
        - grsync
        - hunspell-de-de-frami
        - hyphen-de
        - keepassxc
#       siehe snap oder flatpak:
#        - libreoffice
#        - libreoffice-help-de
#        - libreoffice-l10n-de
#        - libreoffice-pdfimport
        - luckybackup
        - nextcloud-desktop
        - remmina
        - skanlite
        - syncthing
        - terminator
        - vlc
##     Gnome/Ubuntu:
        - alacarte
        - dconf-cli
        - deluge
        - guake
        - gufw
        - inkscape
        - language-pack-gnome-de-base
        - language-pack-gnome-de
        - nemo
        - nemo-nextcloud
        - python3-psutil
        - rhythmbox
        - searchmonkey
        - ufw
##      KDE Plasma
#       - 
#
#
###     Repos needed:
#        -vivaldi-stable
#       Flatpak:
#        - flatpak
#        - gnome-software-plugin-flatpak
#       Snap:
#        - snapd
#
###     Snap Apps (Ubuntu):
#        - chromium
#        - discord
#        - gdu-disk-usage-analyzer
#        - joplin-james-carroll
#        - ksnip
#        - libreoffice
#        - signal-desktop
#        - thunderbird
#        - whalebird
###     flatpak Apps:
#        -
#
#
###     Server:
#        - openssh-server
#
#
###      Virtualization:
##       QEMU - KVM:
#        Ubuntu:
#         - qemu-kvm
#         - libvirt-daemon-system
#         - libvirt-clients
#         - bridge-utils
#         - virtinst
#         - virt-manager
#         - virt-viewer

  - name: add ansible user
    user:
      name: s_ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_s_ansible
      dest: /etc/sudoers.d/s_ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: s_ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sanmue/ansible_test.git
