- name: cleanup package cache (apt)
  tags: always,cleanup
  apt:
    autoclean: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: autoremove orphan packages (apt)
  tags: always,cleanup
  apt:
    autoremove: yes 
    purge: yes
  when: ansible_pkg_mgr == "apt"


- name: clean package cache und orphan packages (pacman)
  tags: always,cleanup
  command: paccache -rk2 -ruk1
  when: ansible_pkg_mgr == "pacman"

# TODO: Suse (zypper)
