- name: cleanup package cache (apt)
  tags: always,cleanup
  apt:
    autoclean: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: autoremove orphan packages (apt)
  tags: always,cleanup
  apt:
    autoremove: yes 
    purge: yes
  when: ansible_pkg_mgr == "apt"

# TODO: Suse (zypper), Arch/Manjaro (pacman)
