- name: add ansible user
  tags: users
  user:
    name: s_ansible
    system: yes

- name: set up sudo for ansible user
  tags: users
  copy:
    src: files/sudoer_s_ansible
    dest: /etc/sudoers.d/s_ansible
    owner: root
    group: root
    mode: 0440

- name: add user 'sandro' to group 'kvm' (Ubuntu)
  user:
    name: sandro
    groups: kvm
    append: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_virtualization_role != "guest"
# noch ohne nested virtualization

- name: add user 'sandro' to group 'libvirt' (openSUSE Leap,Archlinux)
  user:
    name: sandro
    groups: libvirt
    append: yes
  when: 
    - ansible_distribution in ["Archlinux", "openSUSE Leap"]
    - ansible_virtualization_role != "guest"
# noch ohne nested virtualization

- name: add user 'sandro' to group 'kvm' (openSUSE Leap,Archlinux)
  user:
    name: sandro
    groups: kvm
    append: yes
  when: 
    - ansible_distribution in ["Archlinux", "openSUSE Leap"]
    - ansible_virtualization_role != "guest"
# noch ohne nested virtualization

