- name: UFW - allow KDE Connect / GSConnect (tcp)
  ufw:
    rule: allow
    port: 1714:1764 
    proto: tcp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall

- name: UFW - allow KDE Connect / GSConnect (upd)
  ufw:
    rule: allow
    port: 1714:1764
    proto: udp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall


- name: UFW - reload
  ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu" and
        firewall.changed
