- name: UFW - enable
  ufw:
    state: enabled
  when: ansible_distribution == "Ubuntu"

#- name: UFW - allow OpenSSH
#  ufw:
#    rule: limit
#    name: OpenSSH
#    comment: OpenSSH
#  when: ansible_distribution == "Ubuntu"

- name: UFW - allow ssh (tcp)
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    comment: ssh (tcp)
  when: ansible_distribution == "Ubuntu"

- name: UFW - reload
  ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu"
