
#######
### apt
#######
- name: add apt signing key for repos (Ubuntu)
  tags: workstation,ubuntu,addrepos,pre
  apt_key:
    url: https://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present
  when:
#    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

- name: add repo for Vivaldi Browser (Ubuntu)
  tags: workstation,ubuntu,addrepos,pre
  apt_repository:
    repo: deb https://repo.vivaldi.com/archive/deb/ stable main
    state: present
    update_cache: yes
  when:
#    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

- name: add repo for flatpak (Ubuntu)
  tags: workstation,ubuntu,addrepos,pre,flatpak
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present
    update_cache: yes
  when:
#    - ansible_distribution == "Ubuntu"
    - ansible_pkg_mgr == "apt"

##########
### zypper
##########

### Leap
#-------
- name: add Packman Repository (openSUSE Leap 15.2)
  tags: workstation,suse,addrepos,pre
  zypper_repository:
    name: Packman Repository
#   Distri-Version noch hart codiert:
    repo: 'http://packman.inode.at/suse/openSUSE_Leap_15.2/'
    state: present
    auto_import_keys: yes
    autorefresh: yes
    enabled: yes
    priority: '90'
  when:
    - ansible_pkg_mgr == "zypper"
    - ansible_distribution == "openSUSE Leap"

- name: add Libdvdcss Repository (openSUSE Leap 15.2)
  tags: workstation,suse,addrepos,pre
  zypper_repository:
    name: Libdvdcss Repository
#   Distri-Version noch hart codiert:
    repo: 'http://opensuse-guide.org/repo/openSUSE_Leap_15.2/'
    state: present
    auto_import_keys: yes
    autorefresh: yes
    enabled: yes
    priority: '90'
  when:
    - ansible_pkg_mgr == "zypper"
    - ansible_distribution == "openSUSE Leap"

#- name: add repo for snappy (openSUSE Leap 15.2)
#  tags: workstation,suse,addrepos,pre,snap
#  zypper_repository:
#    name: snappy-repo
##   Distri-Version noch hart codiert:
#    repo: 'https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.2'
#    state: present
#    auto_import_keys: yes
#    autorefresh: yes
#    enabled: yes
#  when:
#    - ansible_pkg_mgr == "zypper"
#    - ansible_distribution == "openSUSE Leap"


### Tumbleweed
# ------------
#- name: add Packman Repository (Tumbleweed)
#  tags: workstation,suse,addrepos,pre
#  zypper_repository:
#    name: Packman Repository
##   Distri-Version noch hart codiert:
#    repo: 'http://packman.inode.at/suse/openSUSE_Tumbleweed/Essentials'
##    repo: 'http://packman.inode.at/suse/openSUSE_Tumbleweed/'
#    state: present
#    auto_import_keys: yes
#    autorefresh: yes
#    enabled: yes
#    priority: '90'
#  when:
#    - ansible_pkg_mgr == "zypper"
#    - ansible_distribution == "openSUSE Tumbleweed"

#- name: add Libdvdcss Repository (Tumbleweed)
#  tags: workstation,suse,addrepos,pre
#  zypper_repository:
#    name: Libdvdcss Repository
##   Distri-Version noch hart codiert:
#    repo: 'http://opensuse-guide.org/repo/openSUSE_Tumbleweed/'
#    state: present
#    auto_import_keys: yes
#    autorefresh: yes
#    enabled: yes
#    priority: '90'
#  when:
#    - ansible_pkg_mgr == "zypper"
#    - ansible_distribution == "openSUSE Tumbleweed"


# TODO: Vivaldi, oder einfach weglassen
### Vivaldi Broser:
# -----------------
## funktioniert so nicht bei .repo: # ###
#- name: add repo for Vivaldi Browser (Suse)
#  tags: workstation,suse,addrepos,pre
#  zypper_repository:
#    name: vivaldi-repo
##    repo: 'https://repo.vivaldi.com/archive/vivaldi-suse.repo'
#    repo: 'https://repo.vivaldi.com/archive/rpm/x86_64'
#    state: present
#    auto_import_keys: yes
#    autorefresh: yes
#    enabled: yes
#  when:
#    - ansible_pkg_mgr == "zypper"

#- name: add repo for Vivaldi Browser (Suse)
#  tags: workstation,suse,addrepos,pre
#  get_url:
#    url: https://repo.vivaldi.com/archive/vivaldi-suse.repo
#    dest: /etc/zypp/repos.d/vivaldi.repo
#  when:
#    - ansible_os_family == "Suse"

#- name: add repo for Vivaldi Browser (Suse)
#  tags: workstation,suse,addrepos,pre
#  command: zypper ar -g https://repo.vivaldi.com/archive/vivaldi-suse.repo
#  args:
#    creates: /etc/zypp/repos.d/vivaldi.repo
#    # kommando nur ausführen, wenn "/etc/zypp/repos.d/vivaldi.repo" nicht vorhanden
#  when:
#    - ansible_pkg_mgr == "zypper"

