- name: start libvirtd
  tags: VM
  service:
    name: libvirtd
    state: started
  when: 
    - ansible_virtualization_role != "guest"
# noch ohne nested virtualization

- name: enable libvirtd
  tags: VM
  service:
    name: libvirtd
    #state: enabled
    enabled: yes
  when:  
    - ansible_virtualization_role != "guest"
# noch ohne nested virtualization

#TODO: ggf. noch nested virtualization
