- name: UFW - allow KDE Connect / GSConnect (tcp)
  ufw:
    rule: allow
    port: 1714:1764 
    proto: tcp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

- name: UFW - allow KDE Connect / GSConnect (upd)
  ufw:
    rule: allow
    port: 1714:1764
    proto: udp
    comment: KDE Connect / GSConnect
  when: ansible_distribution == "Ubuntu"
  register: firewall_ufw

- name: UFW - reload
  ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu" and
        firewall_ufw.changed



- name: firewalld - allow KDE Connect
  firewalld:
    service: kdeconnect
    permanent: yes
    state: enabled
    immediate: yes
  when:
    - ansible_distribution in ["Archlinux", "Suse"]
  register: firewall_d

- name: firewalld - reload
  command: firewall-cmd --reload
  when:
    - ansible_distribution in ["Archlinux", "Suse"]
    - firewall_d.changed
