- name: UFW - enable
  ufw:
    state: enabled
  when: ansible_distribution == "Ubuntu"
  register: firewall

#- name: UFW - allow OpenSSH
#  ufw:
#    rule: limit
#    name: OpenSSH
#    comment: OpenSSH
#  when: ansible_distribution == "Ubuntu"

- name: UFW - allow ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    comment: SSH
  when: ansible_distribution == "Ubuntu"
  register: firewall

- name: UFW - reload
  ufw:
    state: reloaded
  when: ansible_distribution == "Ubuntu" and
        firewall.changed


