- name: install additional packages for workstations (Ubuntu,Suse)
  tags: workstation,ubuntu,suse
  package:
    state: latest
    name:
      - vivaldi-stable
  when:
    - ansible_distribution in ["Ubuntu", "Suse"]

- name: install additional packages for workstations (Archlinux)
  tags: workstation,arch
  package:
    state: latest
    name:
      - vivaldi
      - vivaldi-ffmpeg-codecs
  when:
    - ansible_distribution in ["Archlinux"]
