- name: install packages for workstations
  package:
    state: latest
    name:
      - clamtk
      - gimp
      - gimp-help-de
      - gparted
      - grsync
      - hunspell-de-de-frami
      - hyphen-de
      - keepassxc
#     aktueller: über snap oder flatpak:
#      - libreoffice
#      - libreoffice-help-de
#      - libreoffice-l10n-de
#      - libreoffice-pdfimport
      - luckybackup
      - nextcloud-desktop
      - remmina
      - skanlite
      - syncthing
      - terminator
      - vlc

- name: install packages for workstations (Ubuntu/Gnome)
  apt:
    state: latest
    name:
      - alacarte
      - dconf-cli
      - deluge
      - guake
      - gufw
      - inkscape
      - language-pack-gnome-de-base
      - language-pack-gnome-de
      - nemo
      - nemo-nextcloud
      - python3-psutil
      - rhythmbox
      - searchmonkey
      - ufw
  when: ansible_distribution_version == "Ubuntu"


#     KDE Plasma
#     - 
#
#
###  Repos needed:
#      -vivaldi-stable
##   Flatpak:
#      - flatpak
#      - gnome-software-plugin-flatpak
##   Snap:
#      - snapd
#
##   Snap Apps (Ubuntu):
#      - chromium
#      - discord
#      - gdu-disk-usage-analyzer
#      - joplin-james-carroll
#      - ksnip
#      - libreoffice
#      - signal-desktop
#      - thunderbird
#      - whalebird
##   flatpak Apps:
#        -
