
#######################################
### NOT depending on Desktop Environmet 
#######################################

- name: Install packages for workstations (basic/all)
  tags: basic, workstation, ubuntu, arch, suse
  package:
    state: latest
    name:
      - anki
      - ansible
      - clamav
      - clamtk
      - curl
      - flatpak
      - gimp
      - gimp-help-de
      - gparted
      - grsync
      - git
      - htop
#      - hyphen-de
      - keepassxc
      - lsb-release
      - nano
      - neofetch
      - remmina
      - rsync
#      - skanlite # eher bei KDE
#      - snapd # bei Suse herausgenommen
#      - syncthing
      - terminator # bei Suse+KDE nicht unbedingt notwendig -> Konsole
      - vlc
      - unzip


- name: install basic packages (Ubuntu)
  tags: basic, ubuntu, workstation
  package:
    state: latest
    name:
      - snapd # bei Suse herausgenommen 
      - gpg
      - openssh-client
      - ssh
      - ufw
  when: ansible_distribution == "Ubuntu"


- name: install basic packages (Archlinux)
  tags: basic, workstation, arch
  package:
    state: latest
    name:
      - snapd # bei Suse herausgenommen 
  when: ansible_distribution in ["Archlinux"]


- name: install basic packages (Archlinux, Suse)
  tags: basic, workstation, arch, suse
  package:
    state: latest
    name:
      - gnupg
      - gpgme
      - ebtables
      - ipset
      - openssh
  when: ansible_distribution in ["Archlinux"] or ansible_os_family == "Suse"
#    - ansible_distribution in ["Archlinux", "openSUSE Leap"]


- name: install basic packages (Suse)
  tags: basic, workstation, Suse
  package:
    state: latest
    name:
      - firewalld
  when: ansible_os_family == "Suse"


- name: Install basic - multimedia packages (Suse)
  tags: workstation,gnome,suse
  package:
    state: latest
    name:
#     ggf. alternativ: https://software.opensuse.org/download/package?package=opensuse-codecs-installer&project=multimedia%3Aapps
      - flac
      - ffmpeg
      - ffmpeg-4
      - gstreamer-plugins-base
      - gstreamer-plugins-good
      - gstreamer-plugins-good-extra
      - gstreamer-plugins-bad
      - gstreamer-plugins-libav      
      - gstreamer-plugins-ugly
      - libavdevice58_10
      - mpeg2dec
      - mpeg4ip
      - vlc-codec-gstreamer
#     nur pacman-repo:
      - gstreamer-plugins-ugly-orig-addon
      - libdvdcss2
      - libxvidcore4
      - vlc-codecs
  when: 
    - ansible_os_family == "Suse"

