- name: install basic packages (all Distros)
  tags: basic
  package:
    state: latest
    name:
      - clamav
      - curl
      - git

      - htop
      - lsb-release
      - nano
      - neofetch
      - rsync
      - unzip

- name: install basic packages (Ubuntu)
  tags: basic
  package:
    state: latest
    name:
      - gpg
      - openssh-client
      - ssh
      - ufw
  when: ansible_distribution == "Ubuntu"

- name: install basic packages (Archlinux, Suse)
  tags: basic
  package:
    state: latest
    name:
      - firewalld
      - gnupg
      - ebtables
      - ipset
      - openssh
  when:
    - ansible_distribution in ["Archlinux", "Suse"]
