
# TODO: reorganisieren (doppelte Auflistungen bei versch. Distro, aber gleiche SW-Pakete)

# - gnome-shell-extensions... # -> separater Task (packages_workstation-gnomeshellstuff.yml

#########
### Gnome
#########
- name: Install packages for workstations (basic/all)
  tags: workstation
  package:
    state: latest
    name:
      - anki
      - clamtk
      - flatpak
      - gimp
      - gimp-help-de
      - gparted
      - grsync
#      - hyphen-de
      - keepassxc
      - remmina
#      - skanlite # eher bei KDE
      - snapd
      - syncthing
      - terminator
      - vlc


- name: Install packages for workstations (Ubuntu + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: latest
    name:
      - alacarte
      - dconf-cli
      - dconf-editor
      - deluge
      - exfat-fuse
      - exfat-utils
      - firefox
      - firefox-locale-de
      - gnome-software-plugin-flatpak
      - guake
      - gufw
      - hunspell-de-de-frami
      - inkscape
      - language-pack-gnome-de-base
      - language-pack-gnome-de
      - luckybackup
      - nemo
      - nemo-nextcloud
      - nextcloud-desktop
      - python3-psutil
      - rhythmbox
      - searchmonkey
  when: 
    - ansible_distribution == "Ubuntu"
    - env_desktop == "ubuntu:gnome"


- name: Install packages for workstations (Archlinux + Gnome)
  tags: workstation,gnome,arch
  package:
    state: latest
    name:
      - alacarte
      - atom
      - chromium
      - dconf-editor
      - deja-dup
#      - deluge # -> transmission-gtk
      - discord
      - evince
      - exfat-utils
      - firefox
      - firefox-i18n-de
      # ---
      # firmware:
      - alsa-firmware
      - b43-fwcutter
      - fwupd
      - gnome-firmware
      - linux-firmware
      - manjaro-firmware
      - sof-firmware
      # ---
      - foliate
#      - flameshot
      - geary
      - gnome-disk-utility
      - gnome-keyring
      - manjaro-keyring
      - archlinux-keyring
      - seahorse
      - gnome-maps
      - gtkhash
      - guake
      - gufw
      - hplip
      - inkscape
      - kdeconnect
      - libreoffice-still
      - libreoffice-still-de
      - lshw
      - malcontent
      - nemo
      - nemo-share
      - nemo-terminal
      - nextcloud-client
      - pamac-flatpak-plugin
      - rhythmbox
      - signal-desktop
#      - thunderbird
#      - thunderbird-i18n-de
      - timeshift
      - timeshift-autosnap
      - torbrowser-launcher
      - transmission-gtk # -> deluge
      - totem # -> vlc
#      - vlc - -> totem
  when: 
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"


- name: Install packages for workstations (Suse + Gnome)
  tags: workstation,gnome,suse
  package:
    state: latest
    name:
      - alacarte
      - chromium
      - dconf-editor
      - deja-dup
#      - deluge # -> transmission-gtk
      - discord
      - eog
      - eog-plugin-exif-display
      - eog-plugin-map
      - eog-plugins
      - evince
      - evolution # -> geary
      - evolution-data-server
      - evolution-data-server-lang
      - evolution-lang
      - evolution-plugin-bogofilter
      - evolution-plugin-spamassassin
      - exfat-utils
      - firewall-config

      # ---
      # firmware:
      - alsa-firmware
      - b43-fwcutter
      - fwupd
      - gnome-firmware
      - kernel-firmware
#      - linux-firmware
#      - sof-firmware
      # ---

      - foliate
#      - flameshot
#      - geary # -> evolution
#      - geary-lang
      - gimp
      - gimp-help
      - gimp-help-de
      - gimp-lang
#      - gimp-ufraw
      - gnome-calendar
      - gnome-calendar-lang
      - gnome-contacts
      - gnome-contacts-lang
      - gnome-disk-utility
      - gnome-disk-utility-lang
      - gnome-documents
      - gnome-documents-lang
      - gnome-keyring
      - gnome-keyring-lang
      - gnome-maps
      - gnome-maps-lang
      - gnome-photos
      - gnome-shell-search-provider-contacts
      - gnome-shell-calendar # Evolution Kalender Unterstützung für GNOME Shell
      - guake
      - guake-lang
#      - gtkhash
      - hplip
      - inkscape
      - inkscape-lang
      - inkscape-extensions-extra
      - inkscape-extensions-gimp
      - kdeconnect-kde
      - kdeconnect-kde-lang
      - libreoffice
      - libreoffice-filters-optional 
      - libreoffice-gnome
      - libreoffice-l10n-de
#      - libreoffice-mailmerge
      - libreofficekit
      - lshw
      - lshw-gui
      - lshw-lang
      - malcontent
      - MozillaFirefox
      - MozillaFirefox-translations-common
      - nemo
      - nemo-lang
      - nemo-extension-emblems
      - nemo-extension-gtkhash
      - nemo-extension-nextcloud
      - nemo-extension-preview
      - nemo-extension-seahorse
      - nemo-extension-share
      - nemo-extension-terminal
      - nemo-extensions-lang
      - nextcloud-desktop
      - nextcloud-desktop-lang
      - rhythmbox
      - rhythmbox-lang
      - seahorse
      - seahorse-daemon
      - seahorse-lang
      - simple-scan
      - simple-scan-lang  
      - syncthing
      - syncthing-gtk
      - syncthing-gtk-lang
      - terminator
      - terminator-lang
#      - thunderbird # -> evolution
#      - thunderbird-i18n-de
#      - timeshift
 #     - timeshift-autosnap
      - torbrowser-launcher
      - transmission-common
      - transmission-gtk # -> deluge
      - transmission-gtk-lang
      - totem # -> vlc
      - totem-lang
      - totem-plugins
#      - vlc - -> totem
  when: 
    - ansible_os_family == "Suse"
    - env_desktop == "gnome"



##############
### KDE Plasma
##############
- name: Install packages for workstations (Archlinux + KDE Plasma)
  tags: workstation,kde,arch
  package:
    state: latest
    name:
      - cantata
      - exfat-utils
      - firefox
      - firefox-i18n-de
      - hunspell-de
      - krita
      - ktorrent
      - man-pages-de
      - mpd
      - nextcloud-client
      - pamac-flatpak-plugin
      - pamac-snap-plugin
      - qt5-translations
      - snapd
#     instead of flatpaks from repos:
      - discord
      - foliate
      - torbrowser-launcher
      - atom
      - chromium
      - libreoffice-still
      - libreoffice-still-de
      - signal-desktop
      - thunderbird
      - thunderbird-i18n-de
      - yakuake
  when:
    - env_desktop == "kde"
    - ansible_distribution == "Archlinux"

- name: Install packages for workstations (KDE Plasma + Suse)
  tags: workstation,kde,suse
  package:
    state: latest
    name:
      - cantata
      - chromium
      - discord
      - discover-backend-flatpak
      - exfat-utils
      - foliate
      - hunspell
      - krita
      - ktorrent
      - libreoffice
      - libreoffice-l10n-de
      - man-pages
      - MozillaFirefox
      - MozillaFirefox-translations-common
      - MozillaThunderbird
      - MozillaThunderbird-translations-common
      - mpd
      - nextcloud-desktop
      - torbrowser-launcher
      - yakuake
  when:
    - env_desktop == "kde"
    - ansible_os_family == "Suse"

