- name: install basic packages (all Distros)
  tags: basic
  package:
    state: latest
    name:
      - clamav
      - curl
      - git
      - htop
      - lsb-release
      - nano
      - neofetch
      - rsync
      - unzip

- name: install basic packages (Ubuntu)
  tags: basic
  package:
    state: latest
    name:
      - gpg
      - openssh-client
      - ssh
      - ufw
  when: ansible_distribution == "Ubuntu"

- name: install basic packages (Archlinux, openSUSE Leap + KDE)
  tags: basic
  package:
    state: latest
    name:
      - firewalld
      - gnupg
      - ebtables
      - ipset
      - openssh
  when:
    - ansible_distribution in ["Archlinux", "openSUSE Leap"]
    - env_desktop == "kde"

- name: install basic packages (Archlinux + Gnome)
  tags: basic
  package:
    state: latest
    name:
      - gpgme
      - libgpg-error
      - openssh
      - ufw
  when: 
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"

- name: install basic packages (Suse + Gnome)
  tags: basic
  package:
    state: latest
    name:
      - firewalld
      - firewalld-lang
      - gpgme
#      - libgpg-error
      - openssh
  when: 
    - ansible_os_family == "Suse"
    - env_desktop == "gnome"

