
- name: install snap packages for workstations (all distros, not Suse)
  tags: workstation,ubuntu,arch,snap #,suse
  snap:
    state: present
    name:
#      - chromium
#      - discord
#      - gdu-disk-usage-analyzer
#      - joplin-james-carroll
#      - ksnip
#      - libreoffice
#      - signal-desktop
#      - thunderbird
      - whalebird
  when: ansible_os_family != "Suse"

