
# - gnome-shell-extensions... # -> separater Task (packages_workstation-gnomeshellstuff.yml

- name: Install packages for workstations (basic/all)
  tags: workstation
  package:
    state: latest
    name:
      - anki
      - clamtk
      - flatpak
      - gimp
      - gimp-help-de
      - gparted
      - grsync
      - hyphen-de
      - keepassxc
      - remmina
      - skanlite
      - snapd
      - syncthing
      - terminator
      - vlc

- name: Install packages for workstations (Ubuntu + Gnome)
  tags: workstation,gnome,ubuntu
  package:
    state: latest
    name:
      - alacarte
      - dconf-cli
      - dconf-editor
      - deluge
      - exfat-fuse
      - exfat-utils
      - firefox
      - firefox-locale-de
      - gnome-software-plugin-flatpak
      - guake
      - gufw
      - hunspell-de-de-frami
      - inkscape
      - language-pack-gnome-de-base
      - language-pack-gnome-de
      - luckybackup
      - nemo
      - nemo-nextcloud
      - nextcloud-desktop
      - python3-psutil
      - rhythmbox
      - searchmonkey
  when: 
    - ansible_distribution == "Ubuntu"
    - env_desktop == "ubuntu:gnome"

- name: Install packages for workstations (Archlinux + Gnome)
  tags: workstation,gnome,arch
  package:
    state: latest
    name:
      - alacarte
      - atom
      - chromium
      - dconf-editor
      - deja-dup
      - deluge # -> transmission-gtk
      - discord
      - evince
      - exfat-utils
      - firefox
      - firefox-i18n-de
      # ---
      # firmware:
      - alsa-firmware
      - b43-fwcutter
      - fwupd
      - gnome-firmware
      - linux-firmware
      - manjaro-firmware
      - sof-firmware
      # ---
      - foliate
#      - flameshot
      - geary
      - gnome-disk-utility
      - gnome-keyring
      - manjaro-keyring
      - archlinux-keyring
      - seahorse
      - gnome-maps
      - gtkhash
      - guake
      - gufw
      - hplip
      - inkscape
      - kdeconnect
      - libreoffice-still
      - libreoffice-still-de
      - lshw
      - malcontent
      - nemo
      - nemo-share
      - nemo-terminal
      - nextcloud-client
      - pamac-flatpak-plugin
      - rhythmbox
      - signal-desktop
#      - thunderbird
#      - thunderbird-i18n-de
      - timeshift
      - timeshift-autosnap
      - torbrowser-launcher
#      - transmission-gtk # -> deluge
      - totem # -> vlc
#      - vlc - -> totem
  when: 
    - ansible_distribution == "Archlinux"
    - env_desktop == "gnome"

- name: Install packages for workstations (Archlinux,Suse + KDE Plasma)
  tags: workstation,kde
  package:
    state: latest
    name:
      - kde-cli-tools
      - krita
      - ktorrent
      - nextcloud-client
      - mpd
      - cantata
      - yakuake
  when:
    - env_desktop == "kde"
    - ansible_distribution in ["Archlinux", "Suse"]

- name: Install packages for workstations (Archlinux + KDE Plasma)
  tags: workstation,kde,arch
  package:
    state: latest
    name:
      - exfat-utils
      - firefox
      - firefox-i18n-de
      - hunspell-de
      - man-pages-de
      - pamac-flatpak-plugin
      - pamac-snap-plugin
      - qt5-translations
      - snapd
#     instead of flatpaks from repos:
      - discord
      - foliate
      - torbrowser-launcher
      - atom
      - chromium
      - libreoffice-still
      - libreoffice-still-de
      - signal-desktop
      - thunderbird
      - thunderbird-i18n-de
  when:
    - env_desktop == "kde"
    - ansible_distribution == "Archlinux"

- name: Install packages for workstations (KDE Plasma + Suse)
  tags: workstation,kde,suse
  package:
    state: latest
    name:
      - firewall-config
  when:
    - env_desktop == "kde"
    - ansible_distribution == "Suse"


#TODO: Suse (snap, ...)

