- name: install VM QEMU/KVM (Ubuntu)
  tags: VM
  apt:
    state: latest
    name:
       - qemu-kvm
       - libvirt-daemon-system
       - libvirt-clients
       - bridge-utils
       - virtinst
       - virt-manager
  when: ansible_distribution == "Ubuntu" and
        ansible_virtualization_role != "guest"
# noch ohne nested virtualization
