- name: install basic packages
  tags: basic
  package:
    state: latest
    name:
      - clamav
      - git
      - gpg
      - htop
      - lsb-release
      - nano
      - neofetch
#      - openssh
      - openssh-client
      - rsync
      - ssh
