- name: install VM QEMU/KVM (Ubuntu)
  tags: VM
  apt:
    state: latest
    name:
       - qemu-kvm
       - libvirt-daemon-system
       - libvirt-clients
       - bridge-utils
       - virtinst
       - virt-manager
       - virt-viewer
  when: ansible_distribution == "Ubuntu" and
        ansible_virtualization_role != "guest"

# TODO: add user to groups
# TODO: Enable and start service

